// 定义国家信息接口
export interface Country {
  code: string;
  name: string;
  chineseName: string;
}

// 导出国家列表，包含代码、英文名和中文名
const countriesList: Country[] = [
  { code: 'AF', name: 'Afghanistan', chineseName: '阿富汗' },
  { code: 'AL', name: 'Albania', chineseName: '阿尔巴尼亚' },
  { code: 'DZ', name: 'Algeria', chineseName: '阿尔及利亚' },
  { code: 'AD', name: 'Andorra', chineseName: '安道尔' },
  { code: 'AO', name: 'Angola', chineseName: '安哥拉' },
  { code: 'AR', name: 'Argentina', chineseName: '阿根廷' },
  { code: 'AM', name: 'Armenia', chineseName: '亚美尼亚' },
  { code: 'AU', name: 'Australia', chineseName: '澳大利亚' },
  { code: 'AT', name: 'Austria', chineseName: '奥地利' },
  { code: 'AZ', name: 'Azerbaijan', chineseName: '阿塞拜疆' },
  { code: 'BS', name: 'Bahamas', chineseName: '巴哈马' },
  { code: 'BH', name: 'Bahrain', chineseName: '巴林' },
  { code: 'BD', name: 'Bangladesh', chineseName: '孟加拉国' },
  { code: 'BB', name: 'Barbados', chineseName: '巴巴多斯' },
  { code: 'BY', name: 'Belarus', chineseName: '白俄罗斯' },
  { code: 'BE', name: 'Belgium', chineseName: '比利时' },
  { code: 'BZ', name: 'Belize', chineseName: '伯利兹' },
  { code: 'BJ', name: 'Benin', chineseName: '贝宁' },
  { code: 'BT', name: 'Bhutan', chineseName: '不丹' },
  { code: 'BO', name: 'Bolivia', chineseName: '玻利维亚' },
  { code: 'BA', name: 'Bosnia and Herzegovina', chineseName: '波斯尼亚和黑塞哥维那' },
  { code: 'BW', name: 'Botswana', chineseName: '博茨瓦纳' },
  { code: 'BR', name: 'Brazil', chineseName: '巴西' },
  { code: 'BN', name: 'Brunei', chineseName: '文莱' },
  { code: 'BG', name: 'Bulgaria', chineseName: '保加利亚' },
  { code: 'BF', name: 'Burkina Faso', chineseName: '布基纳法索' },
  { code: 'BI', name: 'Burundi', chineseName: '布隆迪' },
  { code: 'KH', name: 'Cambodia', chineseName: '柬埔寨' },
  { code: 'CM', name: 'Cameroon', chineseName: '喀麦隆' },
  { code: 'CA', name: 'Canada', chineseName: '加拿大' },
  { code: 'CV', name: 'Cape Verde', chineseName: '佛得角' },
  { code: 'CF', name: 'Central African Republic', chineseName: '中非共和国' },
  { code: 'TD', name: 'Chad', chineseName: '乍得' },
  { code: 'CL', name: 'Chile', chineseName: '智利' },
  { code: 'CN', name: 'China', chineseName: '中国' },
  { code: 'CO', name: 'Colombia', chineseName: '哥伦比亚' },
  { code: 'KM', name: 'Comoros', chineseName: '科摩罗' },
  { code: 'CG', name: 'Congo', chineseName: '刚果共和国' },
  { code: 'CD', name: 'Congo (DRC)', chineseName: '刚果民主共和国' },
  { code: 'CR', name: 'Costa Rica', chineseName: '哥斯达黎加' },
  { code: 'HR', name: 'Croatia', chineseName: '克罗地亚' },
  { code: 'CU', name: 'Cuba', chineseName: '古巴' },
  { code: 'CY', name: 'Cyprus', chineseName: '塞浦路斯' },
  { code: 'CZ', name: 'Czech Republic', chineseName: '捷克共和国' },
  { code: 'DK', name: 'Denmark', chineseName: '丹麦' },
  { code: 'DJ', name: 'Djibouti', chineseName: '吉布提' },
  { code: 'DM', name: 'Dominica', chineseName: '多米尼克' },
  { code: 'DO', name: 'Dominican Republic', chineseName: '多米尼加共和国' },
  { code: 'EC', name: 'Ecuador', chineseName: '厄瓜多尔' },
  { code: 'EG', name: 'Egypt', chineseName: '埃及' },
  { code: 'SV', name: 'El Salvador', chineseName: '萨尔瓦多' },
  { code: 'GQ', name: 'Equatorial Guinea', chineseName: '赤道几内亚' },
  { code: 'ER', name: 'Eritrea', chineseName: '厄立特里亚' },
  { code: 'EE', name: 'Estonia', chineseName: '爱沙尼亚' },
  { code: 'ET', name: 'Ethiopia', chineseName: '埃塞俄比亚' },
  { code: 'FJ', name: 'Fiji', chineseName: '斐济' },
  { code: 'FI', name: 'Finland', chineseName: '芬兰' },
  { code: 'FR', name: 'France', chineseName: '法国' },
  { code: 'GA', name: 'Gabon', chineseName: '加蓬' },
  { code: 'GM', name: 'Gambia', chineseName: '冈比亚' },
  { code: 'GE', name: 'Georgia', chineseName: '格鲁吉亚' },
  { code: 'DE', name: 'Germany', chineseName: '德国' },
  { code: 'GH', name: 'Ghana', chineseName: '加纳' },
  { code: 'GR', name: 'Greece', chineseName: '希腊' },
  { code: 'GT', name: 'Guatemala', chineseName: '危地马拉' },
  { code: 'GN', name: 'Guinea', chineseName: '几内亚' },
  { code: 'GW', name: 'Guinea-Bissau', chineseName: '几内亚比绍' },
  { code: 'GY', name: 'Guyana', chineseName: '圭亚那' },
  { code: 'HT', name: 'Haiti', chineseName: '海地' },
  { code: 'HN', name: 'Honduras', chineseName: '洪都拉斯' },
  { code: 'HK', name: 'Hong Kong', chineseName: '中国香港' },
  { code: 'HU', name: 'Hungary', chineseName: '匈牙利' },
  { code: 'IS', name: 'Iceland', chineseName: '冰岛' },
  { code: 'IN', name: 'India', chineseName: '印度' },
  { code: 'ID', name: 'Indonesia', chineseName: '印度尼西亚' },
  { code: 'IR', name: 'Iran', chineseName: '伊朗' },
  { code: 'IQ', name: 'Iraq', chineseName: '伊拉克' },
  { code: 'IE', name: 'Ireland', chineseName: '爱尔兰' },
  { code: 'IL', name: 'Israel', chineseName: '以色列' },
  { code: 'IT', name: 'Italy', chineseName: '意大利' },
  { code: 'CI', name: 'Ivory Coast', chineseName: '科特迪瓦' },
  { code: 'JM', name: 'Jamaica', chineseName: '牙买加' },
  { code: 'JP', name: 'Japan', chineseName: '日本' },
  { code: 'JO', name: 'Jordan', chineseName: '约旦' },
  { code: 'KZ', name: 'Kazakhstan', chineseName: '哈萨克斯坦' },
  { code: 'KE', name: 'Kenya', chineseName: '肯尼亚' },
  { code: 'KI', name: 'Kiribati', chineseName: '基里巴斯' },
  { code: 'KP', name: 'North Korea', chineseName: '朝鲜' },
  { code: 'KR', name: 'South Korea', chineseName: '韩国' },
  { code: 'KW', name: 'Kuwait', chineseName: '科威特' },
  { code: 'KG', name: 'Kyrgyzstan', chineseName: '吉尔吉斯斯坦' },
  { code: 'LA', name: 'Laos', chineseName: '老挝' },
  { code: 'LV', name: 'Latvia', chineseName: '拉脱维亚' },
  { code: 'LB', name: 'Lebanon', chineseName: '黎巴嫩' },
  { code: 'LS', name: 'Lesotho', chineseName: '莱索托' },
  { code: 'LR', name: 'Liberia', chineseName: '利比里亚' },
  { code: 'LY', name: 'Libya', chineseName: '利比亚' },
  { code: 'LI', name: 'Liechtenstein', chineseName: '列支敦士登' },
  { code: 'LT', name: 'Lithuania', chineseName: '立陶宛' },
  { code: 'LU', name: 'Luxembourg', chineseName: '卢森堡' },
  { code: 'MO', name: 'Macau', chineseName: '中国澳门' },
  { code: 'MK', name: 'North Macedonia', chineseName: '北马其顿' },
  { code: 'MG', name: 'Madagascar', chineseName: '马达加斯加' },
  { code: 'MW', name: 'Malawi', chineseName: '马拉维' },
  { code: 'MY', name: 'Malaysia', chineseName: '马来西亚' },
  { code: 'MV', name: 'Maldives', chineseName: '马尔代夫' },
  { code: 'ML', name: 'Mali', chineseName: '马里' },
  { code: 'MT', name: 'Malta', chineseName: '马耳他' },
  { code: 'MH', name: 'Marshall Islands', chineseName: '马绍尔群岛' },
  { code: 'MR', name: 'Mauritania', chineseName: '毛里塔尼亚' },
  { code: 'MU', name: 'Mauritius', chineseName: '毛里求斯' },
  { code: 'MX', name: 'Mexico', chineseName: '墨西哥' },
  { code: 'FM', name: 'Micronesia', chineseName: '密克罗尼西亚' },
  { code: 'MD', name: 'Moldova', chineseName: '摩尔多瓦' },
  { code: 'MC', name: 'Monaco', chineseName: '摩纳哥' },
  { code: 'MN', name: 'Mongolia', chineseName: '蒙古' },
  { code: 'ME', name: 'Montenegro', chineseName: '黑山' },
  { code: 'MA', name: 'Morocco', chineseName: '摩洛哥' },
  { code: 'MZ', name: 'Mozambique', chineseName: '莫桑比克' },
  { code: 'MM', name: 'Myanmar', chineseName: '缅甸' },
  { code: 'NA', name: 'Namibia', chineseName: '纳米比亚' },
  { code: 'NR', name: 'Nauru', chineseName: '瑙鲁' },
  { code: 'NP', name: 'Nepal', chineseName: '尼泊尔' },
  { code: 'NL', name: 'Netherlands', chineseName: '荷兰' },
  { code: 'NZ', name: 'New Zealand', chineseName: '新西兰' },
  { code: 'NI', name: 'Nicaragua', chineseName: '尼加拉瓜' },
  { code: 'NE', name: 'Niger', chineseName: '尼日尔' },
  { code: 'NG', name: 'Nigeria', chineseName: '尼日利亚' },
  { code: 'NO', name: 'Norway', chineseName: '挪威' },
  { code: 'OM', name: 'Oman', chineseName: '阿曼' },
  { code: 'PK', name: 'Pakistan', chineseName: '巴基斯坦' },
  { code: 'PW', name: 'Palau', chineseName: '帕劳' },
  { code: 'PS', name: 'Palestine', chineseName: '巴勒斯坦' },
  { code: 'PA', name: 'Panama', chineseName: '巴拿马' },
  { code: 'PG', name: 'Papua New Guinea', chineseName: '巴布亚新几内亚' },
  { code: 'PY', name: 'Paraguay', chineseName: '巴拉圭' },
  { code: 'PE', name: 'Peru', chineseName: '秘鲁' },
  { code: 'PH', name: 'Philippines', chineseName: '菲律宾' },
  { code: 'PL', name: 'Poland', chineseName: '波兰' },
  { code: 'PT', name: 'Portugal', chineseName: '葡萄牙' },
  { code: 'QA', name: 'Qatar', chineseName: '卡塔尔' },
  { code: 'RO', name: 'Romania', chineseName: '罗马尼亚' },
  { code: 'RU', name: 'Russia', chineseName: '俄罗斯' },
  { code: 'RW', name: 'Rwanda', chineseName: '卢旺达' },
  { code: 'KN', name: 'Saint Kitts and Nevis', chineseName: '圣基茨和尼维斯' },
  { code: 'LC', name: 'Saint Lucia', chineseName: '圣卢西亚' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', chineseName: '圣文森特和格林纳丁斯' },
  { code: 'WS', name: 'Samoa', chineseName: '萨摩亚' },
  { code: 'SM', name: 'San Marino', chineseName: '圣马力诺' },
  { code: 'ST', name: 'Sao Tome and Principe', chineseName: '圣多美和普林西比' },
  { code: 'SA', name: 'Saudi Arabia', chineseName: '沙特阿拉伯' },
  { code: 'SN', name: 'Senegal', chineseName: '塞内加尔' },
  { code: 'RS', name: 'Serbia', chineseName: '塞尔维亚' },
  { code: 'SC', name: 'Seychelles', chineseName: '塞舌尔' },
  { code: 'SL', name: 'Sierra Leone', chineseName: '塞拉利昂' },
  { code: 'SG', name: 'Singapore', chineseName: '新加坡' },
  { code: 'SK', name: 'Slovakia', chineseName: '斯洛伐克' },
  { code: 'SI', name: 'Slovenia', chineseName: '斯洛文尼亚' },
  { code: 'SB', name: 'Solomon Islands', chineseName: '所罗门群岛' },
  { code: 'SO', name: 'Somalia', chineseName: '索马里' },
  { code: 'ZA', name: 'South Africa', chineseName: '南非' },
  { code: 'SS', name: 'South Sudan', chineseName: '南苏丹' },
  { code: 'ES', name: 'Spain', chineseName: '西班牙' },
  { code: 'LK', name: 'Sri Lanka', chineseName: '斯里兰卡' },
  { code: 'SD', name: 'Sudan', chineseName: '苏丹' },
  { code: 'SR', name: 'Suriname', chineseName: '苏里南' },
  { code: 'SZ', name: 'Eswatini', chineseName: '斯威士兰' },
  { code: 'SE', name: 'Sweden', chineseName: '瑞典' },
  { code: 'CH', name: 'Switzerland', chineseName: '瑞士' },
  { code: 'SY', name: 'Syria', chineseName: '叙利亚' },
  { code: 'TW', name: 'Taiwan', chineseName: '中国台湾' },
  { code: 'TJ', name: 'Tajikistan', chineseName: '塔吉克斯坦' },
  { code: 'TZ', name: 'Tanzania', chineseName: '坦桑尼亚' },
  { code: 'TH', name: 'Thailand', chineseName: '泰国' },
  { code: 'TL', name: 'Timor-Leste', chineseName: '东帝汶' },
  { code: 'TG', name: 'Togo', chineseName: '多哥' },
  { code: 'TO', name: 'Tonga', chineseName: '汤加' },
  { code: 'TT', name: 'Trinidad and Tobago', chineseName: '特立尼达和多巴哥' },
  { code: 'TN', name: 'Tunisia', chineseName: '突尼斯' },
  { code: 'TR', name: 'Turkey', chineseName: '土耳其' },
  { code: 'TM', name: 'Turkmenistan', chineseName: '土库曼斯坦' },
  { code: 'TV', name: 'Tuvalu', chineseName: '图瓦卢' },
  { code: 'UG', name: 'Uganda', chineseName: '乌干达' },
  { code: 'UA', name: 'Ukraine', chineseName: '乌克兰' },
  { code: 'AE', name: 'United Arab Emirates', chineseName: '阿联酋' },
  { code: 'GB', name: 'United Kingdom', chineseName: '英国' },
  { code: 'US', name: 'United States', chineseName: '美国' },
  { code: 'UY', name: 'Uruguay', chineseName: '乌拉圭' },
  { code: 'UZ', name: 'Uzbekistan', chineseName: '乌兹别克斯坦' },
  { code: 'VU', name: 'Vanuatu', chineseName: '瓦努阿图' },
  { code: 'VA', name: 'Vatican City', chineseName: '梵蒂冈' },
  { code: 'VE', name: 'Venezuela', chineseName: '委内瑞拉' },
  { code: 'VN', name: 'Vietnam', chineseName: '越南' },
  { code: 'YE', name: 'Yemen', chineseName: '也门' },
  { code: 'ZM', name: 'Zambia', chineseName: '赞比亚' },
  { code: 'ZW', name: 'Zimbabwe', chineseName: '津巴布韦' }
];

export default countriesList; 